openapi: 3.0.0
info:
  title: 日志系统-API
  version: '1.0'
paths:
  /api/pmp/axUploadImage:
    post:
      summary: 上传单张图片
      description: ''
      operationId: 'App\Controller\Api\PmpController::axUploadImage'
      parameters:
        -
          name: image
          in: query
          description: 图片
          required: true
          schema:
            type: image
      responses: {  }
