openapi: 3.0.0
info:
  title: 日志系统-前台-API
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://xw.mr-gut.cn'
    description: 测试域名
  -
    url: 'http://coop.mr-gut.cn'
    description: 正式域名
paths:
  /api/pmpf/axGetDailyDetail:
    get:
      tags:
        - 基础
      summary: 获取一个日志详情
      operationId: axGetDailyDetail
      parameters:
        -
          name: uuid
          in: query
          description: 日志UUID
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  rt: { description: 返回值, type: integer, example: '1' }
                  daily: { description: 日志详情, properties: { id: { description: ID, type: integer }, title: { description: 简介, type: string }, time: { description: 时间, type: string } }, type: object, example: { id: 1, title: 点点滴滴, time: '2020-03-19' } }
                  contents: { description: 日志内容数组, type: array, items: { properties: { id: { description: 日志内容ID, type: integer }, title: { description: 模块标题, type: string }, work_summary: { description: 工作纪要, type: array, items: { type: string } }, measures: { description: 推进措施, type: array, items: { type: string } }, other: { description: 其他说明, type: array, items: { type: string } } }, type: object } }
                  dailyList: { description: 更多日报列表, type: array, items: { properties: { id: { description: 日报ID, type: integer }, title: { description: 简介, type: string }, time: { description: 日期, type: string }, timeCh: { description: 日期-中文, type: string }, detaultUrl: { description: 跳转链接, type: string } }, type: object } }
                  files: { description: 日志附件数组, type: array, items: { properties: { file: { description: 文件路径, type: string }, fileOss: { description: 文件路径-PC端用, type: string }, fileFull: { description: 文件路径-移动端用, type: string } }, type: object } }
                type: object
  /api/pmpf/axGetFiles:
    post:
      tags:
        - 基础
      summary: 获取文件管理列表
      operationId: axGetFiles
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                type:
                  description: 文件类型
                  type: string
                format:
                  description: 文件格式
                  type: string
                time:
                  description: 日期
                  type: string
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  rt: { description: 返回值, type: integer, example: '1' }
                  params: { $ref: '#/components/schemas/SearchParams' }
                  pageParams: { $ref: '#/components/schemas/PageParams' }
                  allTypes: { description: 文件类型筛选项, $ref: '#/components/schemas/SearchSelectOptions' }
                  allFormats: { description: 文件格式筛选项, $ref: '#/components/schemas/SearchSelectOptions' }
                  allTimes: { description: 日期筛选项, $ref: '#/components/schemas/SearchSelectOptions' }
                  items: { description: 列表数组, type: array, items: { properties: { id: { description: ID, type: integer }, fileName: { description: 文件名称, type: string }, file: { description: 文件, type: string }, fileOss: { description: 文件-PC端用, type: string }, fileFull: { description: 文件-移动端端用, type: string }, time: { description: 发布日期, type: string } }, type: object } }
                type: object
  /api/pmpf/axGetPageInfo:
    get:
      tags:
        - 基础
      summary: 获取页面基础信息
      operationId: axGetPageInfo
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  loginUser: { description: 用户信息, properties: { id: { description: 用户ID, type: integer }, nickname: { description: 昵称, type: string }, name: { description: 姓名, type: string }, avatar: { description: 头像, type: string } }, type: object }
                  pageTitle: { description: 页面标题, type: string }
                  pageDesc: { description: 页面描述, type: string }
                  followGzh: { description: 是否关注公众号, type: boolean }
                  isMobile: { description: 是否移动端, type: boolean }
                  isWeixin: { description: 是否微信端, type: boolean }
                  loginUrl: { description: 登录链接, type: string }
                  signPackage: { description: 微信js需要的数据, properties: { appId: { description: appId, type: string }, nonceStr: { description: nonceStr, type: string }, timestamp: { description: timestamp, type: string }, signature: { description: signature, type: string } }, type: object }
                  shareInfo: { description: 分享信息, properties: { title: { description: 标题, type: string }, description: { description: 描述, type: string }, image: { description: 图片, type: string }, link: { description: 链接, type: string } }, type: object }
                type: object
  /api/pmpf/axGetReportInfo:
    get:
      tags:
        - 基础
      summary: 获取研报信息
      operationId: axGetReportInfo
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  rt: { description: 返回值, type: integer, example: '1' }
                  url: { description: 详情URL, type: string }
                type: object

components:
  schemas:
    OptionItem:
      allOf:
        -
          $ref: '#/components/schemas/OptionItem'
        -
          properties:
            value:
              description: 值
              type: string
            label:
              description: Label
              type: string
          type: object
    SearchSelectOptions:
      description: 列表搜索select筛选项
      allOf:
        -
          $ref: '#/components/schemas/SearchSelectOptions'
        -
          type: array
          items:
            $ref: '#/components/schemas/OptionItem'
    SearchParams:
      description: 列表搜索参数
      type: object
      allOf:
        -
          $ref: '#/components/schemas/SearchParams'
        -
          properties:
            more:
              description: 更多参见搜索项
              type: string
          type: object
          example:
            more: 更多参见搜索项
    PageParams:
      description: 分页数据
      type: object
      allOf:
        -
          $ref: '#/components/schemas/PageParams'
        -
          properties:
            page:
              description: 页码
              type: integer
            limit:
              description: 页码
              type: integer
            count:
              description: 总数
              type: integer
          type: object
          example:
            page: 1
            limit: 20
            count: '100'
