openapi: 3.0.0
info:
  title: 搜索-前台-API
  description: ''
  version: 1.0.0
servers:
  -
    url: 'https://xx.mr-gut.cn'
    description: 测试域名
  -
    url: 'https://www.mr-gut.cn'
    description: 正式域名
paths:
  /api/search/axGetSuggest:
    get:
      tags:
        - 搜索
      summary: '1.1 搜索时，获取下拉推荐词'
      operationId: axGetSuggest
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                term:
                  description: Term
                  type: string
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  rt: { description: 返回值, type: integer, example: '1' }
                  suggestions: { description: 搜索建议列表, type: array, items: { type: string } }
                type: object
  /api/search/axSearchPoint:
    get:
      tags:
        - 搜索
      summary: '1.2 获取热门词和搜索历史'
      operationId: axSearchPoint
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  rt: { description: 返回值, type: integer, example: '1' }
                  historyList: { description: 搜索历史, $ref: '#/components/schemas/SearchSelectOptions' }
                  hotwordList: { description: 热门词列表, $ref: '#/components/schemas/SearchSelectOptions' }
                type: object
  /api/search/axClearSearchHistory:
    get:
      tags:
        - 搜索
      summary: '1.3 清除搜索历史'
      operationId: axClearSearchHistory
      parameters: []
  /api/search/axSimpleSearch:
    get:
      tags:
        - 搜索
      summary: '2.1 通用搜索'
      operationId: axSimpleSearch
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                md:
                  description: 模块：all->全部；p->日报；z->智库；a->官网文章；
                  type: string
                term:
                  description: Term【历史记录｜热门】
                  type: string
                q:
                  description: 输入框搜索内容【输入框】
                  type: string
                title:
                  description: 标题【高级】
                  type: string
                doi:
                  description: DOI【高级】
                  type: string
                periodical:
                  description: 发表期刊【高级｜筛选】
                  type: string
                ifs:
                  description: 影响因子：最小【高级】
                  type: string
                ife:
                  description: 影响因子：最大【高级】
                  type: string
                ys:
                  description: 发表时间：开始【高级】
                  type: string
                ye:
                  description: 发表时间：截止【高级】
                  type: string
                author:
                  description: 作者名称【高级｜筛选】
                  type: string
                author_country:
                  description: 作者国家【高级｜筛选】
                  type: string
                author_district:
                  description: 地区【筛选】
                  type: string
                author_school:
                  description: 机构【筛选】
                  type: string
                keywords:
                  description: 关键词【高级｜筛选】
                  type: string
                type:
                  description: 类型【筛选】
                  type: string
                year:
                  description: 发表时间【筛选】
                  type: string
                impact_factor:
                  description: 影响因子【筛选】
                  type: string
                limit:
                  description: 每页展示条数，默认20条【分页】
                  type: string
                page:
                  description: 分页的第几页，默认为1【分页】
                  type: string
                sort:
                  description: '排序方式：''''=>相关性排序；if=>影响因子；time=>发表时间【排序】'
                  type: string
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  rt: { description: 返回值, type: integer, example: '1' }
                type: object

components:
  schemas:
    OptionItem:
      allOf:
        -
          $ref: '#/components/schemas/OptionItem'
        -
          properties:
            value:
              description: 值
              type: string
            label:
              description: Label
              type: string
          type: object
    SearchSelectOptions:
      description: 列表搜索select筛选项
      allOf:
        -
          $ref: '#/components/schemas/SearchSelectOptions'
        -
          type: array
          items:
            $ref: '#/components/schemas/OptionItem'
    SearchParams:
      description: 列表搜索参数
      type: object
      allOf:
        -
          $ref: '#/components/schemas/SearchParams'
        -
          properties:
            more:
              description: 更多参见搜索项
              type: string
          type: object
          example:
            more: 更多参见搜索项
    PageParams:
      description: 分页数据
      type: object
      allOf:
        -
          $ref: '#/components/schemas/PageParams'
        -
          properties:
            page:
              description: 页码
              type: integer
            limit:
              description: 页码
              type: integer
            count:
              description: 总数
              type: integer
          type: object
          example:
            page: 1
            limit: 20
            count: '100'
