openapi: 3.0.0
info:
  title: 商城小程序-中台-API
  description: ''
  version: '1.1'
servers:
  -
    url: 'http://xw.mr-gut.cn'
    description: 测试域名
  -
    url: 'http://st.mr-gut.cn'
    description: 正式域名
paths:
  /api/store/axGetStockLogs:
    post:
      tags:
        - 库存管理
      summary: 获取库存管理列表数据
      operationId: axGetStockLogs
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                product_name:
                  description: 商品名称
                  type: string
                product_code:
                  description: 商品编码
                  type: string
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  rt: { description: 返回值, type: integer, example: '1' }
                  params: { $ref: '#/components/schemas/SearchParams' }
                  pageParams: { $ref: '#/components/schemas/PageParams' }
                  stat: { description: 统计详情, properties: { inCount: { description: 入库数量, type: integer }, outCount: { description: 出库数量, type: string }, remainingCount: { description: 剩余数量, type: string } }, type: object }
                  items: { description: 列表数组, type: array, items: { properties: { id: { description: ID, type: integer }, user_id: { description: 用户ID, type: integer }, userName: { description: 用户名称, type: string }, type: { description: 类型：in->入库；out->出库, type: string }, typeStr: { description: 类型：in->入库；out->出库, type: string }, product_name: { description: 商品名称, type: string }, product_code: { description: 商品编码, type: string }, product_count: { description: 商品数量, type: integer }, order_id: { description: 订单ID, type: integer }, order_sn: { description: 订单编码, type: string }, seller_id: { description: 销售员ID, type: integer }, sellerName: { description: 销售员姓名, type: string }, agent_id: { description: 代理商ID, type: integer }, agentName: { description: 代理商姓名, type: string }, chater_id: { description: 业务员ID, type: integer }, chaterName: { description: 业务员姓名, type: string }, saled: { description: 已确认售出：0->未确认1->已确认, type: integer }, saled_time: { description: 已确认售出时间, type: string }, remark: { description: 备注信息, type: string }, created: { description: 创建时间, type: string } }, type: object } }
                type: object

components:
  schemas:
    OptionItem:
      allOf:
        -
          $ref: '#/components/schemas/OptionItem'
        -
          properties:
            value:
              description: 值
              type: string
            label:
              description: Label
              type: string
          type: object
    SearchSelectOptions:
      description: 列表搜索select筛选项
      allOf:
        -
          $ref: '#/components/schemas/SearchSelectOptions'
        -
          type: array
          items:
            $ref: '#/components/schemas/OptionItem'
    SearchParams:
      description: 列表搜索参数
      type: object
      allOf:
        -
          $ref: '#/components/schemas/SearchParams'
        -
          properties:
            more:
              description: 更多参见搜索项
              type: string
          type: object
          example:
            more: 更多参见搜索项
    PageParams:
      description: 分页数据
      type: object
      allOf:
        -
          $ref: '#/components/schemas/PageParams'
        -
          properties:
            page:
              description: 页码
              type: integer
            limit:
              description: 页码
              type: integer
            count:
              description: 总数
              type: integer
          type: object
          example:
            page: 1
            limit: 20
            count: '100'
