openapi: 3.0.0
info:
  title: 智库-前台-API
  description: ''
  version: 1.0.0
servers:
  -
    url: 'https://xx.mr-gut.cn'
    description: 测试域名
  -
    url: 'https://www.mr-gut.cn'
    description: 正式域名
paths:
  /api/zhikuf/axUploadFile:
    post:
      tags:
        - 基础
      summary: '1.2 上传单个附件'
      operationId: axUploadFile
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
              properties:
                file:
                  description: 附件
                  type: file
                  format: binary
                useOriginFileName:
                  description: 是否使用原文件名称
                  type: bool
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  rt: { description: 返回值, type: integer }
                  file: { description: 附件路径, type: string }
                  fileOss: { description: 附件全路径, type: string }
                type: object
                example:
                  rt: 1
                  file: /articles/200326/261fda515213ad83b641f902edd94dfe.pdf
                  fileOss: 'https://pics-xldkp-com.oss-cn-qingdao.aliyuncs.com/articles/200326/261fda515213ad83b641f902edd94dfe.pdf'
  /api/zhikuf/axPubRecomArticle:
    post:
      tags:
        - 专家自荐文章
      summary: '2.1 智库专家上传自己的新文章'
      operationId: axPubRecomArticle
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - zhiku_id
                - src_url
              properties:
                zhiku_id:
                  description: 智库ID
                  type: integer
                src_url:
                  description: 'PDF地址,先用axUploadFile上传文件获得一个相对路径的地址'
                  type: string
                summary:
                  description: 简要概括
                  type: string
                pubtime:
                  description: 发布时间
                  type: string
                periodical:
                  description: 期刊名称
                  type: string
                post_status:
                  description: 发表状态：accepted->已接受；online->已上线;
                  type: string
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  rt: { description: 返回值, type: integer, example: '1' }
                  id: { description: 数据ID, type: integer, example: '1' }
                type: object
  /api/zhikuf/axGetRecomArticles:
    post:
      tags:
        - 专家自荐文章
      summary: '2.2 获取智库专家已上传的文章列表'
      description: 不分页
      operationId: axGetRecomArticles
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                zhiku_id:
                  description: 智库ID
                  type: integer
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  rt: { description: 返回值, type: integer, example: '1' }
                  items: { description: 列表数组, type: array, items: { properties: { id: { description: ID, type: integer }, fileName: { description: 文件名称, type: string }, fileOss: { description: 文件-PC端用, type: string }, fileFull: { description: 文件-移动端端用, type: string }, summary: { description: 简要概括, type: string }, pubtime: { description: 发布时间, type: string }, periodical: { description: 期刊名称, type: string }, post_status: { description: 发表状态：accepted->已接受；online->已上线;, type: string }, postStatusStr: { description: 发表状态：accepted->已接受；online->已上线;, type: string }, audit_status: { description: 审核状态：waiting->待审核；pass->审核通过；fail->审核未通过, type: string }, auditStatusStr: { description: 审核状态：waiting->待审核；pass->审核通过；fail->审核未通过, type: string } }, type: object } }
                type: object

components:
  schemas:
    OptionItem:
      allOf:
        -
          $ref: '#/components/schemas/OptionItem'
        -
          properties:
            value:
              description: 值
              type: string
            label:
              description: Label
              type: string
          type: object
    SearchSelectOptions:
      description: 列表搜索select筛选项
      allOf:
        -
          $ref: '#/components/schemas/SearchSelectOptions'
        -
          type: array
          items:
            $ref: '#/components/schemas/OptionItem'
    SearchParams:
      description: 列表搜索参数
      type: object
      allOf:
        -
          $ref: '#/components/schemas/SearchParams'
        -
          properties:
            more:
              description: 更多参见搜索项
              type: string
          type: object
          example:
            more: 更多参见搜索项
    PageParams:
      description: 分页数据
      type: object
      allOf:
        -
          $ref: '#/components/schemas/PageParams'
        -
          properties:
            page:
              description: 页码
              type: integer
            limit:
              description: 页码
              type: integer
            count:
              description: 总数
              type: integer
          type: object
          example:
            page: 1
            limit: 20
            count: '100'
